name: logger-go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Build & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.13.8']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use golang ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Restore golang cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go-version}}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version}}
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: |
          make setup
          make install

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test

      - name: Enforce coverage
        run: make enforce

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report-go
          path: coverage.out